


notice:
	cp -rf $(KERNEL_DRV_ROOT)/COPYING $(OSS_NOTICE_OUTPUT)/kernel_NOTICE.txt
	
info:
	echo $(KERNEL_VER)  $(subst linux-,,$(KERNEL_VER))
	cp -rf OSS_INFO.$(subst linux-,,$(KERNEL_VER)).txt $(OSS_INFO_OUTPUT)/kernel_INFO.txt
