/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein is
 * confidential and proprietary to MediaTek Inc. and/or its licensors. Without
 * the prior written permission of MediaTek inc. and/or its licensors, any
 * reproduction, modification, use or disclosure of MediaTek Software, and
 * information contained herein, in whole or in part, shall be strictly
 * prohibited.
 *
 * MediaTek Inc. (C) 2016-2017. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER
 * ON AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
 * NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH
 * RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 * INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES
 * TO LOOK ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO.
 * RECEIVER EXPRESSLY ACKNOWLEDGES THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO
 * OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES CONTAINED IN MEDIATEK
 * SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE
 * RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S
 * ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE
 * RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE
 * MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE
 * CHARGE PAID BY RECEIVER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek
 * Software") have been modified by MediaTek Inc. All revisions are subject to
 * any receiver's applicable license agreements with MediaTek Inc.
 */


/* FILE NAME:  u_bt_mw_leaudio_common.h
 * AUTHOR:
 * PURPOSE:
 *      It provides bluetooth leaudio bms profile structure to APP.
 * NOTES:
 */
#ifndef _U_BT_MW_LEAUDIO_COMMON_H_
#define _U_BT_MW_LEAUDIO_COMMON_H_

#include "u_bt_mw_common.h"

#define BT_BROADCAST_MAX_BIG_NUM (31) //real big num should less than max adv advertising set the fw support
#define BT_BROADCAST_MAX_SUBGROUP_NUM (4)
#define BT_BROADCAST_MAX_BIS_NUM (4)
#define BT_BROADCAST_METADATA_SIZE (251)
#define BT_BROADCAST_BROADCAST_CODE_SIZE (16)
#define BT_BROADCAST_SOCKET_INDEX_NUM (4)
#define BT_UNICAST_METADATA_SIZE (251)
#define BT_UNICAST_MAX_DEVICE_SIZE (2)
#define BT_UNICAST_DEV_MAX_ASE_SIZE (2)


/* Audio Allocations */
#define BT_LE_AUDIO_ALLOCATION_NONE (0x00000000)
#define BT_LE_AUDIO_ALLOCATION_FRONTLEFT (0x00000001)
#define BT_LE_AUDIO_ALLOCATION_FRONTRIGHT (0x00000002)
#define BT_LE_AUDIO_ALLOCATION_FRONTCENTER (0x00000004)
#define BT_LE_AUDIO_ALLOCATION_LOWFREQEFFECTS1 (0x00000008)
#define BT_LE_AUDIO_ALLOCATION_BACKLEFT (0x00000010)
#define BT_LE_AUDIO_ALLOCATION_BACKRIGHT (0x00000020)
#define BT_LE_AUDIO_ALLOCATION_FRONTLEFTOFCENTER (0x00000040)
#define BT_LE_AUDIO_ALLOCATION_FRONTRIGHTOFCENTER (0x00000080)
#define BT_LE_AUDIO_ALLOCATION_BACKCENTER (0x00000100)
#define BT_LE_AUDIO_ALLOCATION_LOWFREQEFFECTS2 (0x00000200)
#define BT_LE_AUDIO_ALLOCATION_SIDELEFT (0x00000400)
#define BT_LE_AUDIO_ALLOCATION_SIDERIGHT (0x00000800)
#define BT_LE_AUDIO_ALLOCATION_TOPFRONTLEFT (0x00001000)
#define BT_LE_AUDIO_ALLOCATION_TOPFRONTRIGHT (0x00002000)
#define BT_LE_AUDIO_ALLOCATION_TOPFRONTCENTER (0x00004000)
#define BT_LE_AUDIO_ALLOCATION_TOPCENTER (0x00008000)
#define BT_LE_AUDIO_ALLOCATION_TOPBACKLEFT (0x00010000)
#define BT_LE_AUDIO_ALLOCATION_TOPBACKRIGHT (0x00020000)
#define BT_LE_AUDIO_ALLOCATION_TOPSIDELEFT (0x00040000)
#define BT_LE_AUDIO_ALLOCATION_TOPSIDERIGHT (0x00080000)
#define BT_LE_AUDIO_ALLOCATION_TOPBACKCENTER (0x00100000)
#define BT_LE_AUDIO_ALLOCATION_BOTTOMFRONTCENTER (0x00200000)
#define BT_LE_AUDIO_ALLOCATION_BOTTOMFRONTLEFT (0x00400000)
#define BT_LE_AUDIO_ALLOCATION_BOTTOMFRONTRIGHT (0x00800000)
#define BT_LE_AUDIO_ALLOCATION_FRONTLEFTWIDE (0x01000000)
#define BT_LE_AUDIO_ALLOCATION_FRONTRIGHTWIDE (0x02000000)
#define BT_LE_AUDIO_ALLOCATION_LEFTSURROUND (0x04000000)
#define BT_LE_AUDIO_ALLOCATION_RIGHTSURROUND (0x08000000)

typedef enum
{
    LE_AUDIO_ALLOCATION_NONE = BT_LE_AUDIO_ALLOCATION_NONE, //0x00000000
    LE_AUDIO_ALLOCATION_MONO_LEFT = BT_LE_AUDIO_ALLOCATION_FRONTLEFT, //0x00000001
    LE_AUDIO_ALLOCATION_MONO_RIGHT = BT_LE_AUDIO_ALLOCATION_FRONTRIGHT, //0x00000002
    LE_AUDIO_ALLOCATION_STEREO_LR = BT_LE_AUDIO_ALLOCATION_FRONTLEFT | BT_LE_AUDIO_ALLOCATION_FRONTRIGHT, //0x00000003
    LE_AUDIO_ALLOCATION_INVALID = 0xFFFFFFFF,
} BT_LE_AUDIO_ALLOCATION_SET;

#endif /*  _U_BT_MW_LEAUDIO_COMMON_H_ */
